name: netmasha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.0
  floating_navigation_bar: ^0.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  molten_navigationbar_flutter: ^1.0.1
  phosphor_flutter: ^2.0.1
  translucent_navigation_bar: ^1.0.0
flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
